login/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name = 'login'

urlpatterns = [
    path('login', views.LoginView.as_view(),name='login'),
    path('signup', views.SignUpView.as_view(),name='signup'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('projects/', views.projects,name='projects'),
    path('materials/', views.materials,name='materials'),
    path('collections/', views.collections,name='collections'),
    path('projects-detail/', views.project_detail,name='projects-detail'),
    path('materials-detail/', views.material_detail,name='materials-detail'),
    path('collections-detail/', views.collection_detail,name='collections-detail'),
    path('', views.menu, name='menu'),
    # path('signup', views.signup,name='signup'),
    # path('signin', views.signin,name='signin'),
    # path('home', views.home,name='home'),
    path('materials-details/<int:pk>', views.material_details,name='materials-details'),
    path('projects-details/<int:pk>', views.project_details,name='projects-details'),
    path('collections-details/<int:pk>', views.collection_details,name='collections-details'),
    path('details/', views.details,name='details'),
    # path('admin/', admin.site.urls),
]

worklogin/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('',include('login.urls')),
    path('admin/', admin.site.urls),
]

login/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.utils.translation import gettext_lazy as _
from .managers import UserManager


class User(AbstractBaseUser, PermissionsMixin):
    """
    Custom User Model
    """

    PROFESSION_CHOICE = (
        (None, 'Profession'),
        ('ART', 'Architect'),
        ('ID', 'Interior Designer'),
        ('DTR', 'Distributer'),
        ('HTL', 'Hotel'),
        ('CTR', 'Contractor'),
        ('PNM', 'Press & Media'),
        ('OTH', 'Others'),
    )

    name = models.CharField(
        _('first name'),
        max_length=150,
    )

    email = models.EmailField(
        _('Email'),
        unique=True,
    )

    company_name = models.CharField(
        _('Company Name'),
        max_length=50,
    )

    website_name = models.CharField(
        _('Website Name'),
        max_length=100,
    )

    profession = models.CharField(
        _('Profession'),
        choices=PROFESSION_CHOICE,
        max_length=3,
        null=True,
        blank=True,
    )

    is_staff = models.BooleanField(
        _('Staff Status'),
        default=False,
    )

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = [
        'name',
    ]

    class Meta:
        ordering = ['-id', ]
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super(self.__class__, self).clean()
        self.email = self.__class__.objects.normalize_email(self.email)

def get_urls(view = "Desktop_View", type = "materials", pk=1, num_img = 5):
    li = ['images/Desktop_View/singapore/' + str(i) + '.jpg' for i in range(1,16)]
    return li

#projects section
class projects:
    def __init__(self, pk, name, num_img, url_list, small_url):
        self.cat = "pro" + str(pk)
        self.pk = pk
        self.name = name
        self.num_img = num_img
        self.url_list = url_list
        self.display = small_url

li = ['images/Desktop_View/singapore/' + str(i) + '.jpg' for i in range(1,16)]
small_url = ['images/Desktop_View/singapore/' + str(i) + '.jpg' for i in range(1,9)]
projects_list = [
    projects(1,'PARK HYATT VIENNAE', 13, li, small_url),
    projects(2,'PRIVATE RESENDENCIES', 5, li, small_url),
    projects(3,'SINGAPORE', 3, li, small_url),
    projects(4,'RIO', 8, li, small_url),
    projects(5,'SHANGHAI', 8, li, small_url),
    projects(6,'PARIS', 6, li, small_url),
    projects(7,'YATCH', 6, li, small_url),
    projects(8,'GRAND HYATT GURGAON', 6, li, small_url),
    projects(9,'CAPETOWN', 6, li, small_url),
    projects(10,'MILAN', 6, li, small_url),
    projects(11,'NEWYORK', 6, li, small_url),
    projects(12,'CLASS 55 YACHT', 6, li, small_url),
    projects(13,'KL WELLNESS CENTER', 6, li, small_url),
    projects(14,'OFFICE', 6, li, small_url),
]


#collections section
class collections:
    def __init__(self, pk, name, num_img, url_list, small_url):
        self.cat = "col" + str(pk)
        self.pk = pk
        self.name = name
        self.num_img = num_img
        self.url_list = url_list
        self.display = small_url

li = ['images/Desktop_View/vases/' + str(i) + '.jpg' for i in range(1,26)]
small_url = ['images/Desktop_View/vases/' + str(i) + '.jpg' for i in range(1,10)]
collections_list = [
    collections(1,'VASES', 13, li, small_url),
    collections(2,'LIGHTS', 13, li, small_url),
    collections(3,'TABLES', 13, li, small_url),
    collections(4,'LAMPS', 13, li, small_url),
    collections(5,'CHAIRS', 13, li, small_url),
    collections(6,'BOWLS', 13, li, small_url),
    collections(7,'CABINS', 13, li, small_url),
    collections(8,'BRASS FURNITURE', 13, li, small_url),
    collections(9,'ACCESSORY SETS', 13, li, small_url),
    collections(10,'BATHROOM SETS', 13, li, small_url),
    collections(11,'BONE & HORN', 13, li, small_url),
    collections(12,'CARPETS', 13, li, small_url),
    collections(13,'CUSHIONS', 13, li, small_url),
    collections(14,'TRAY', 13, li, small_url),
]


#materials section
class materials:
    def __init__(self, pk, name, num_img, url_list,col_list=[],pro_list=[]):
        self.cat = "mat" + str(pk)
        self.pk = pk
        self.name = name
        self.num_img = num_img
        self.url_list = url_list
        self.collections = col_list
        self.projects = pro_list
        self.display = url_list[:8]

li = ['images/Desktop_View/selenite/' + str(i) + '.jpg' for i in range(1,23)]
materials_list = [
    materials(1,'SEMI PRECIOUS STONE', 13, li, [1,3,5], [2,3]),
    materials(2,'STRAW MACQUERTY', 13, li, [2,3], [1,]),
    materials(3,'GLASS', 13, li, [5,], [1,4]),
    materials(4,'MOTHER OF PEARL', 13, li, [6,7], [3,5]),
    materials(5,'STONE', 13, li),
    materials(6,'SELENITE', 13, li),
    materials(7,'STINGRAY', 13, li),
    materials(8,'GRAND HYATT GURGAON', 13, li),
    materials(9,'BRASS', 13, li),
    materials(10,'LEATHER', 13, li),
    materials(11,'WOOD', 13, li),
    materials(12,'PARCHMENT', 13, li),
    materials(13,'BONE', 13, li),
    materials(14,'BONE', 13, li),
    materials(15,'HORN', 13, li),
    materials(16,'LEAFING', 13, li),
    materials(17,'LACQUERWARE', 13, li),
    materials(18,'NATURE MATERIAL', 13, li),
]

login/forms.py
from login import models
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import get_user_model

User = get_user_model()

class SignUpForm(forms.ModelForm):
    """
    Customer Signup Form
    """
    password1 = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'type':'password', 'class': 'form-control', 'placeholder':"Enter Password"},))
    password2 = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'type':'password', 'class': 'form-control', 'placeholder':"Enter Password"},))

    class Meta:
        model = User
        fields = (
            'name',
            'email',
            'company_name',
            'website_name',
            'profession',
            'password1',
            'password2',
        )

    def __init__(self, *args, **kwargs):
        super(self.__class__, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['placeholder'] = 'Name'
        self.fields['email'].widget.attrs['placeholder'] = 'Email'
        self.fields['company_name'].widget.attrs['placeholder'] = 'Company Name'
        self.fields['website_name'].widget.attrs['placeholder'] = 'Website Name'
        self.fields['password1'].widget.attrs['placeholder'] = 'Enter Password'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'
        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['company_name'].widget.attrs['class'] = 'form-control'
        self.fields['website_name'].widget.attrs['class'] = 'form-control'
        

    def clean(self):
        cleaned_data = super(self.__class__, self).clean()
        if cleaned_data.get('password1') != cleaned_data.get('password2'):
            raise forms.ValidationError({'password2': 'Both password must be same'})
        return cleaned_data

    def save(self, commit=True):
        user = super(self.__class__, self).save(commit=False)
        user.set_password(self.cleaned_data['password2'])
        if commit:
            user.save()
        return user            


class Loginform(AuthenticationForm):
    """
    Custom Login Form
    """

    def __init__(self, *args, **kwargs):
        super(self.__class__, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'Email'
        self.fields['password'].widget.attrs['placeholder'] = 'Password'
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password'].widget.attrs['class'] = 'form-control'
        self.fields['password'].widget.attrs['type'] = 'password'

login/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User
from django.contrib import messages
from django import forms
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.views.generic import FormView
from django.urls import reverse_lazy

from .forms import SignUpForm, Loginform

from .models import projects_list, collections_list, materials_list
from .mixins import AlreadyAuthenticated

# # Create your views here.
# def loginpage(request):
#     # logout(request)
#     form = signinform()
#     form2 = loginform()
#     context = {'form':form,'form2':form2}
#     return render(request,'login.html',context)


# def signup(request):
#     if request.method == 'POST':
#         form = signinform(request.POST)
#         if form.is_valid():
#             print("valid")
#             form.save()
#             username = form.cleaned_data.get('username')
#             raw_password = form.cleaned_data.get('password1')
#             user = authenticate(username=username, password=raw_password)
#             login(request,user)
#             return render(request,'projects.html')
#         else:
#             print("invalid")
#     form = signinform()
#     context = {'form':form}
#     return render(request,'login.html',context)

# from django.contrib.auth import authenticate, login
# from django.contrib.auth.forms import AuthenticationForm
# def signin(request):
#     if request.method == 'POST':
#         formi = AuthenticationForm(data=request.POST)
#         if formi.is_valid():
#             user = formi.get_user()
#             login(request, user)
#             return redirect('/menu/')
#     form = signinform()
#     form2 = loginform()
#     context = {'form':form,'form2':form2}
#     return render(request,'login.html',context)

# def home(request):
#     logout(request)
#     form = signinform()
#     form2 = loginform()
#     context = {'form':form,'form2':form2}
#     return render(request,'login.html',context)


class LoginView(AlreadyAuthenticated, LoginView):
    """
    Login view
    """
    form_class = Loginform
    template_name = 'login.html'
    redirect_authenticated_user = True


class SignUpView(AlreadyAuthenticated, FormView):
    """Customer SignUp View"""
    form_class = SignUpForm
    template_name = 'signup.html'
    success_url = 'login:signup'

    def form_valid(self, form):
        self.object = form.save()
        email = form.cleaned_data.get('email')
        password = form.cleaned_data.get('password1')
        user = authenticate(username=email, password=password)
        if user and user.is_active:
            login(self.request, user)
            if self.request.GET.get('next'):
                return redirect(self.request.GET.get('next'))
            else:
                self.success_url = reverse_lazy('login:menu')
        return super(self.__class__, self).form_valid(form)


@login_required
def menu(request):
    return render(request,'menu.html',{"pro_list" : projects_list, "col_list" : collections_list,"mat_list" : materials_list})

@login_required
def projects(request):
    return render(request,'projects.html',{"data" : projects_list,})

@login_required
def materials(request):
    return render(request,'materials.html',{"data" : materials_list,})

@login_required
def collections(request):
    return render(request,'collections.html',{"data" : collections_list,})


@login_required
def project_detail(request):
    pro_req = []
    if request.method == 'GET':
        lis = list(request.GET.keys())
        for pro in projects_list:
            if str(pro.pk) in lis:
                pro_req.append(pro)
    if len(pro_req)==0:
        pro_req = projects_list[:3]
    return render(request,'projects_detail.html',{"data" : pro_req,})


@login_required
def collection_detail(request):
    col_req = []
    if request.method == 'GET':
        lis = list(request.GET.keys())
        for col in collections_list:
            if str(col.pk) in lis:
                col_req.append(col)
    if len(col_req)==0:
        col_req = collections_list[:3]
    return render(request,'collections_detail.html',{"data" : col_req,})



@login_required
def material_detail(request):
    mat_req = []
    if request.method == 'GET' or pk==0:
        lis = list(request.GET.keys())
        for mat in materials_list:
            if str(mat.pk) in lis:
                mat_req.append(mat)
    if len(mat_req)==0:
        mat_req = materials_list[:3]
    return render(request,'material_detail.html',{"data" : mat_req,})


@login_required
def material_details(request,pk=0):
        mat_req = []
        if pk!=0:
            for mat in materials_list:
                if str(mat.pk) == str(pk):
                    mat_req.append(mat)
        if len(mat_req)==0:
            mat_req = materials_list[:3]
        return render(request,'material_detail.html',{"data" : mat_req,})


@login_required
def collection_details(request,pk):
    col_req = []
    if pk!=0:
        for col in collections_list:
            if str(col.pk) == str(pk):
                col_req.append(col)
    if len(col_req)==0:
        col_req = collections_list[:3]
    return render(request,'collections_detail.html',{"data" : col_req,})


@login_required
def project_details(request,pk):
    pro_req = []
    if pk!=0:
        for pro in projects_list:
            if str(pro.pk) == str(pk):
                pro_req.append(pro)
    if len(pro_req)==0:
        pro_req = projects_list[:3]
    return render(request,'projects_detail.html',{"data" : pro_req,})

@login_required
def details(request):
    mat, col, pro, mat_req, col_req, pro_req = [], [], [], [], [], []
    if request.method == 'GET' or pk==0:
        lis = list(request.GET.keys())
        print(lis)
        for li in lis:
            if "mat" in li:
                mat.append(int(li.replace('mat',"")))
            elif "col" in li:
                col.append(int(li.replace('col',"")))
            elif "pro" in li:
                pro.append(int(li.replace('pro',"")))
        print(mat,col,pro)

    if len(mat)>0:
        for material in materials_list:
            if int(material.pk) in mat:
                mat_req.append(material)
    if len(col)>0:
        for collection in collections_list:
            if int(collection.pk) in col:
                col_req.append(collection)
    if len(pro)>0:
        for project in projects_list:
            if int(project.pk) in pro:
                pro_req.append(project)
                
    if len(mat_req)==0 and len(col_req) == 0 and len(pro_req)==0:
        mat_req = materials_list[:1]
        col_req = collections_list[:1]
        pro_req = projects_list[:1]

    context = {'mat_list': mat_req, 'col_list' : col_req, 'pro_list' : pro_req, 'projects_list': projects_list, 'collections_list': collections_list}
    return render(request, 'details.html', context)

templates/collections.html
{% extends "frame.html" %}
{% load static %}
{% block customheadend %}

{% endblock %}

{% block page-content %}
    <section class="project-section">
        <div class="pos-rel project-banner">
            <img src="{% static 'images/Desktop_View/collection/collection-banner.jpg'%}">
            <h3>COLLECTIONS</h3>
        </div>
        <div class="container-fluid pos-rel">

            <div class="row custom-back-btn mb-5">
                <div class="col-lg-2 col-md-2 col-3 text-center">
                    <div class="back-btn-wrapper">
                    <a href="{% url 'login:collections' %}">
                        <h4 class="font-primary-color mb-0">BACK</h4>
                        <div class="back-btn"></div>
                    </a>
                    </div>
                </div>
                <div class="col-lg-8 col-md-8 col-9">
                    <div class="dropdown">
                    <button
                        type="button"
                        class="btn-menu-project dropdown-toggle"
                        data-toggle="dropdown"
                    >
                        What are you looking for?
                        <i class="fa fa-search ml-lg-5 ml-md-5 ml-2"></i>
                    </button>
                    <div class="dropdown-menu ListingDropDownMaterials ml-0">
                        <div class="row">
                        <div class="col-12">
                            <h2 class="menu-list-heading">COLLECTIONS</h2>
                        </div>

                        <form class="w-100" action="{% url 'login:collections-detail' %}" method="GET">
                          <div class="Listing w-100">
                            <div class="w-100">
                                <div class="d-block">
                                  {% for mat in data %}
                                    <div class="d-flex mx-auto text-left align-items-baseline">
                                        <input type="checkbox" name="{{ mat.pk }}" class="mr-2" />
                                        <div class="main-heading text-gray text-left">
                                          {{ mat.name }}
                                        </div>
                                    </div>
                                  {%endfor%}
                                </div>
                            </div>
                          </div>

                            <div class="d-block text-center mt-5">
                            <button type="submit" class="menu-search-btn">SEARCH</button>
                            </div>
                        </form>
                        </div>
                    </div>
                    </div>
                </div>
                <div class="col-lg-2 col-md-2"></div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-6 mt-lg-3 mt-md-3 col-md-6 mb-3 mb-lg-0 mb-md-0">
                    <div class="project-img-wrapper">
                      <a href="{% url 'login:collections-details' 1 %}">
                        <img src="{% static 'images/Desktop_View/collection/vases.jpg'%}">
                        <div class="project-bottom-text">
                            <h3 class="mb-0">VASES</h3>
                        </div>
                      </a>
                    </div>
                </div>
                <div class="col-lg-6 mt-lg-3 mt-md-3 col-md-6 mb-3 mb-lg-0 mb-md-0">
                    <div class="project-img-wrapper">
                        <a href="{% url 'login:collections-details' 2 %}">
                            <img src="{% static 'images/Desktop_View/collection/lights.jpg'%}">
                            <div class="project-bottom-text">
                                <h3 class="mb-0">LIGHTS</h3>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-6 mt-lg-3 mt-md-3 col-md-6 mb-3 mb-lg-0 mb-md-0">
                    <div class="project-img-wrapper">
                        <a href="{% url 'login:collections-details' 3 %}">
                            <img src="{% static 'images/Desktop_View/collection/tables.jpg'%}">
                            <div class="project-bottom-text">
                                <h3 class="mb-0">TABLES</h3>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-6 mt-lg-3 mt-md-3 col-md-6 mb-3 mb-lg-0 mb-md-0">
                    <div class="project-img-wrapper">
                        <a href="{% url 'login:collections-details' 4 %}">
                            <img src="{% static 'images/Desktop_View/collection/lamps.jpg'%}">
                            <div class="project-bottom-text">
                                <h3 class="mb-0">LAMPS</h3>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-6 mt-lg-3 mt-md-3 col-md-6 mb-3 mb-lg-0 mb-md-0">
                    <div class="project-img-wrapper">
                        <a href="{% url 'login:collections-details' 5 %}">
                            <img src="{% static 'images/Desktop_View/collection/chairs.jpg'%}">
                            <div class="project-bottom-text">
                                <h3 class="mb-0">CHAIRS</h3>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-6 mt-lg-3 mt-md-3 col-md-6 mb-3 mb-lg-0 mb-md-0">
                    <div class="project-img-wrapper">
                        <a href="{% url 'login:collections-details' 6 %}">
                            <img src="{% static 'images/Desktop_View/collection/bowls.jpg'%}">
                            <div class="project-bottom-text">
                                <h3 class="mb-0">BOWLS</h3>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-6 mt-lg-3 mt-md-3 col-md-6 mb-3 mb-lg-0 mb-md-0">
                    <div class="project-img-wrapper">
                        <a href="{% url 'login:collections-details' 7 %}">
                            <img src="{% static 'images/Desktop_View/collection/cabins.jpg'%}">
                            <div class="project-bottom-text">
                                <h3 class="mb-0">CABINS</h3>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-6 mt-lg-3 mt-md-3 col-md-6 mb-3 mb-lg-0 mb-md-0">
                    <div class="project-img-wrapper">
                        <a href="{% url 'login:collections-details' 8 %}">
                            <img src="{% static 'images/Desktop_View/collection/brass-furniture.jpg'%}">
                            <div class="project-bottom-text">
                                <h3 class="mb-0">BRASS FURNITURE</h3>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-6 mt-lg-3 mt-md-3 col-md-6 mb-3 mb-lg-0 mb-md-0">
                    <div class="project-img-wrapper">
                        <a href="{% url 'login:collections-details' 9 %}">
                            <img src="{% static 'images/Desktop_View/collection/accessory-sets.jpg'%}">
                            <div class="project-bottom-text">
                                <h3 class="mb-0">ACCESSORY SETS</h3>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-6 mt-lg-3 mt-md-3 col-md-6 mb-3 mb-lg-0 mb-md-0">
                    <div class="project-img-wrapper">
                        <a href="{% url 'login:collections-details' 10 %}">
                            <img src="{% static 'images/Desktop_View/collection/bathroom-sets.jpg'%}">
                            <div class="project-bottom-text">
                                <h3 class="mb-0">BATHROOM SETS</h3>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-6 mt-lg-3 mt-md-3 col-md-6 mb-3 mb-lg-0 mb-md-0">
                    <div class="project-img-wrapper">
                        <a href="{% url 'login:collections-details' 11 %}">
                            <img src="{% static 'images/Desktop_View/collection/bone_horn.jpg'%}">
                            <div class="project-bottom-text">
                                <h3 class="mb-0">BONE & HORN</h3>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-6 mt-lg-3 mt-md-3 col-md-6 mb-3 mb-lg-0 mb-md-0">
                    <div class="project-img-wrapper">
                        <a href="{% url 'login:collections-details' 12 %}">
                            <img src="{% static 'images/Desktop_View/collection/carpets.jpg'%}">
                            <div class="project-bottom-text">
                                <h3 class="mb-0">CARPETS</h3>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-6 mt-lg-3 mt-md-3 col-md-6 mb-3 mb-lg-0 mb-md-0">
                    <div class="project-img-wrapper">
                        <a href="{% url 'login:collections-details' 13 %}">
                            <img src="{% static 'images/Desktop_View/collection/cushions.jpg'%}">
                            <div class="project-bottom-text">
                                <h3 class="mb-0">CUSHIONS</h3>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-6 mt-lg-3 mt-md-3 col-md-6 mb-3 mb-lg-0 mb-md-0">
                    <div class="project-img-wrapper">
                        <a href="{% url 'login:collections-details' 14 %}">
                            <img src="{% static 'images/Desktop_View/collection/tray.jpg'%}">
                            <div class="project-bottom-text">
                                <h3 class="mb-0">TRAY</h3>
                            </div>
                        </a>
                    </div>
                </div>


            </div>
        </div>
    </section>
{% endblock page-content %}



{% block custombodyend %}

{% endblock %}

templates/collections_detail.html
{% extends "frame.html" %}
{% load static %}
{% block customheadend %}
    <link rel="stylesheet" href="{% static 'css/masonary-grid.css'%}">
{% endblock %}

{% block page-content %}
<div class="container-fluid mt-5 masonary-grid pos-rel">
  <div class="back-btn-wrapper-detail">
    <a href="{% url 'login:collections' %}">
      <h4>BACK</h4>
      <div class="back-btn"></div>
    </a>
    </div>
  <!-- <div class="masonry"> -->
    {% for col in data %}
          <h3>{{ col.name }}</h3>
    <div class="masonry">

          {%for i in col.url_list %}
    				<div class="brick">
              {% static i as myphoto %}
    					<img src = "{{ myphoto }}">
              <div class="img-overlay zoom-gallery">
                <a href="{{ myphoto }}" class="img-icon">
                  <img src = "{{ myphoto }}" class="d-none">
                  <i class="fas fa-search-plus"></i>
                </a>
                <a href="{{ myphoto }}" class="download-icon" download>
                  <img src = "{{ myphoto }}" class="d-none">
                  <i class="fas fa-download"></i>
                </a>
              </div>
    				</div>
          {%endfor%}
          </div>
        {% endfor %}




</div>

{% endblock page-content %}



{% block custombodyend %}
<script>

  $(document).ready(function(){
    $('.zoom-gallery').magnificPopup({
        delegate: 'a',
        type: 'image',
        closeOnContentClick: false,
        closeBtnInside: false,
        mainClass: 'mfp-with-zoom mfp-img-mobile',
        image: {
            verticalFit: true,
        },
        gallery: {
            enabled: true
        },
        zoom: {
            enabled: true,
            duration: 300, // don't foget to change the duration also in CSS
            opener: function (element) {
                return element.find('img');
            }
        }

    });
  })

</script>
{% endblock %}

templates/frame.html
{% extends "base.html" %}

{% block content %}

{% include "components/header.html" %}

{% block page-content %}



{% endblock page-content %}

{% include "components/footer.html" %}

{% endblock content %}

templates/material_detail.html
{% extends "frame.html" %}
{% load static %}
{% block customheadend %}
    <link rel="stylesheet" href="{% static 'css/masonary-grid.css'%}">
{% endblock %}

{% block page-content %}
<div class="container-fluid mt-5 masonary-grid pos-rel">
  <div class="back-btn-wrapper-detail">
      <a href="{% url 'login:materials' %}">
        <h4>BACK</h4>
        <div class="back-btn"></div>
      </a>
    </div>
    {% for mat in data %}
      <h3>{{ mat.name }}</h3>
      <div class="masonry">
        {%for i in mat.url_list %}

          <div class="brick">
            {% static i as myphoto %}
            <img src = "{{ myphoto }}">
            <div class="img-overlay zoom-gallery">
              <a href="{{ myphoto }}" class="img-icon">
                <img src = "{{ myphoto }}" class="d-none">
                <i class="fas fa-search-plus"></i>
              </a>
              <a href="{{ myphoto }}" class="download-icon" download>
                  <img src = "{{ myphoto }}" class="d-none">
                <i class="fas fa-download"></i>
              </a>
            </div>
          </div>

        {%endfor%}
      </div>
    {% endfor %}
</div>

{% endblock page-content %}



{% block custombodyend %}
<script>

  $(document).ready(function(){
    $('.zoom-gallery').magnificPopup({
        delegate: 'a',
        type: 'image',
        closeOnContentClick: false,
        closeBtnInside: false,
        mainClass: 'mfp-with-zoom mfp-img-mobile',
        image: {
            verticalFit: true,
        },
        gallery: {
            enabled: true
        },
        zoom: {
            enabled: true,
            duration: 300, // don't foget to change the duration also in CSS
            opener: function (element) {
                return element.find('img');
            }
        }

    });
  })

</script>
{% endblock %}