login/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name = 'login'

urlpatterns = [
    path('login', views.LoginView.as_view(),name='login'),
    path('signup', views.SignUpView.as_view(),name='signup'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('projects/', views.projects,name='projects'),
    path('materials/', views.materials,name='materials'),
    path('collections/', views.collections,name='collections'),
    path('projects-detail/', views.project_detail,name='projects-detail'),
    path('materials-detail/', views.material_detail,name='materials-detail'),
    path('collections-detail/', views.collection_detail,name='collections-detail'),
    path('', views.menu, name='menu'),
    # path('signup', views.signup,name='signup'),
    # path('signin', views.signin,name='signin'),
    # path('home', views.home,name='home'),
    path('materials-details/<int:pk>', views.material_details,name='materials-details'),
    path('projects-details/<int:pk>', views.project_details,name='projects-details'),
    path('collections-details/<int:pk>', views.collection_details,name='collections-details'),
    path('details/', views.details,name='details'),
    # path('admin/', admin.site.urls),
]

worklogin/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('',include('login.urls')),
    path('admin/', admin.site.urls),
]

templates/components/footer.html
{% load static %}
<section class="footer mt-lg-3">
    <div class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="footer-logo">
                        <div class="icon"><img src="{% static 'images/logo_icon.svg'%}" alt="logo"></div>
                        <div class="icon-text"><img src="{% static 'images/logo_text.svg'%}" alt="logo"></div>
                        <div class="tag-line"><img src="{% static 'images/tagline.svg'%}" alt="logo"></div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="footer-menu">
                        <ul>
                           <li><a href="{% url 'login:menu' %}">Uncharted Design</a></li>
                            <li><a href="{% url 'login:materials' %}">Material</a></li>
                            <li><a href="{% url 'login:projects' %}">Project</a></li>
                            <li><a href="{% url 'login:collections' %}">Collection</a></li>
                            <li><a href="{% url 'login:logout' %}">Logout</a></li>
                        </ul>
                    </div>
                    <div class="social-icons">
                        <ul>
                            <li><a href="/"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="/"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="/"><i class="fa fa-instagram"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-4"></div>
            </div>
        </div>
    </div>
</section>
{% comment %} <section class="footer mt-lg-3">
    <div class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="footer-logo">
                        <div class="icon"><img src="{% static 'images/logo_icon.svg'%}" alt="logo"></div>
                        <div class="icon-text"><img src="{% static 'images/logo_text.svg'%}" alt="logo"></div>
                        <div class="tag-line"><img src="{% static 'images/tagline.svg'%}" alt="logo"></div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="footer-menu">
                        <ul>
                            <li><a href="about_us.html">Home</a></li>
                            <li><a href="{% url 'login:menu' %}">Our Story</a></li>
                            <li><a href="materials.html">Materials</a></li>
                            <li><a href="work_preview.html">Work</a></li>
                            <li><a href="contact_us.html">Contact</a></li>
                        </ul>
                    </div>
                    <div class="social-icons">
                        <ul>
                            <li><a href="/"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="/"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="/"><i class="fa fa-instagram"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-4"></div>
            </div>
        </div>
    </div>
</section> {% endcomment %}